# Clash Nyanpasu Config

app_singleton_port: null
app_log_level: info
language: zh
theme_mode: dark
theme_blur: false
traffic_graph: true
enable_memory_usage: true
lighten_animation_effects: false
enable_tun_mode: true
enable_service_mode: true
enable_auto_launch: true
enable_silent_start: true
enable_system_proxy: true
enable_proxy_guard: false
system_proxy_bypass: ''
proxy_guard_duration: 30
theme_setting:
  primary_color: '#fff'
  secondary_color: null
  primary_text: null
  secondary_text: null
  info_color: null
  error_color: null
  warning_color: null
  success_color: null
  font_family: null
  css_injection: null
  page_transition_duration: null
web_ui_list: null
clash_core: mihomo
hotkeys: null
auto_close_connection: true
default_latency_test: null
enable_clash_fields: true
enable_builtin_enhanced: true
proxy_layout_column: null
auto_log_clean: null
max_log_files: 7
window_size_state:
  width: 1214
  height: 642
  x: 0
  y: 0
  maximized: false
  fullscreen: false
enable_random_port: false
verge_mixed_port: 7890
enable_auto_check_update: true
clash_strategy:
  external_controller_port_strategy: fixed
clash_tray_selector: normal
always_on_top: false
tun_stack: mixed
